Use OpenStack Router IP
stackitcloud/gardener-extension-acl pull request #16
Opened 2022-12-13 14:05 UTC by SimonKienzler

For OpenStack infrastructures, this change will read the router IP from the modified Infrastructure object.

It requires a temporary replace of the upstream `github.com/gardener/gardener-extension-provider-openstack` package with the `github.com/stackitcloud/gardener-extension-provider-openstack` package, until https://github.com/gardener/gardener-extension-provider-openstack/pull/520 is merged and a new version is published.

Boy Scout addition: Updated dependencies and switched to embedded `charts` directory.

2022-12-13 14:35 UTC, breuerfelix requested changes

2022-12-13 14:35 UTC, breuerfelix commented on pkg/webhook/webhook.go
> +		fmt.Printf("\n\nAlways Allowed CIDRs: %+v\n\n", alwaysAllowedCIDRs)
i guess its a leftover

2022-12-13 15:47 UTC, breuerfelix commented
we should wait for https://github.com/gardener/gardener-extension-provider-openstack/pull/520 to be merged and use this repo as the `go.mod` dependency.

LGTM

2022-12-14 14:03 UTC, SimonKienzler commented
For adding arbitrary CIDRs via the `ControllerDeployment` values, some more additions to the code were required. Also, some fixes were needed for the Helm chart (RBAC) to make it work on the seeds. @breuerfelix PTAL

2022-12-15 07:52 UTC, breuerfelix approved these changes

2022-12-15 08:33 UTC, merged